source "http://rubygems.org"

gem "middleman", :github => "middleman/middleman"
gem "susy", "~> 1.0.rc.0"
gem "modular-scale", "~> 0.0.5"
gem "redcarpet", ">= 3.5.1"
gem "rack-codehighlighter", :git => "git://github.com/wbzyl/rack-codehighlighter.git"
gem "pygments.rb", ">= 0.3.0"
gem "listen", "~> 0.4.2"
